//! Editor module containing the core QuillAI Editor component and related functionality.
//!
//! This module provides:
//! - The main `QuillAIEditor` component
//! - Component props definition (generated by component macro)
//! - Internal state management
//! - Integration with Delta and Parchment systems

pub mod component;
pub mod contenteditable;
pub mod delta_integration;
pub mod delta_operations;
pub mod dom_integration;
pub mod input_handler;
pub mod integration_tests;
pub mod parchment_integration;
// pub mod state;

// Re-export main types
pub use component::{QuillAIEditor, QuillAIEditorProps};
