//! Editor module containing the core QuillAI Editor component and related functionality.
//!
//! This module provides:
//! - The main `QuillAIEditor` component
//! - Component props definition (generated by component macro)
//! - Internal state management
//! - Integration with Delta and Parchment systems

pub mod component;
pub mod state;

// Re-export main types
pub use component::{QuillAIEditor, QuillAIEditorProps};
